### ISSUE TITLE
Breaks touchscreen tiling, btw. no touchscreen support at all

### ISSUE THREAD

**Issue by thelazy6** [Leleat/Tiling-Assist#42]
**Describe the bug**
When activated, gnome-shell's builtin functionality of dragging a title bar with a finger to left/right edge for tiling stops working.

**Steps To Reproduce**
Install on a touchscreen device of your choice and try to tile using touchscreen

**Screenshots/-captures**
- Extension disabled:
https://user-images.githubusercontent.com/62787185/111128890-b9cfc000-8575-11eb-87e7-7b1822b4eab4.mp4

- Extension enabled:
https://user-images.githubusercontent.com/62787185/111128896-bb998380-8575-11eb-8435-774354941ccd.mp4
Touch tiling broken, mouse tiling ok.

**System Info:**
 - Distro (incl. version): Manjaro 20.2.1 (Linux 5.11)
 - GNOME version: 3.38.3
 - Extensions version: 13
 - Wayland

**Comment by Leleat** [comment]
I don't see anything in your videos. Nothing is happening for me in both videos (with Extension enabled or disabled). Could you retry?

**Comment by thelazy6** [comment]
Use attached WEBM videos (I think it is a conversion issue of the
videos). Github unfortunately doesn't upload WEBM.

Am Montag, dem 15.03.2021 um 10:48 -0700 schrieb Leleat:

**Comment by Leleat** [comment]
> Use attached WEBM videos
You didn't attach videos to your comment or sending them via mail just didn't work properly.

**Comment by Turbine1991** [comment]
The videos play okay for me in Chrome.

**Comment by Leleat** [comment]
> The videos play okay for me in Chrome.

Whoops, it does, my bad.

**Comment by Leleat** [comment]
Unfortunately I don't have a touch device running linux, so I hope you can help me debug a bit. 

I've created a branch https://github.com/Leleat/Tiling-Assist/tree/touch-grab., which prints something to the logs. Please install the branch (don't forget to restart gnome shell), and then run ` journalctl -fo cat /usr/bin/gnome-shell` in a Terminal. After that try to tile a window again via touch. Do the location coordinates of your finger get printed? If not, did at least `touch event gotten` get printed?

**Comment by Turbine1991** [comment]
> I've created a branch https://github.com/Leleat/Tiling-Assist/tree/touch-grab., which prints something to the logs. Please install the branch (don't forget to restart gnome shell), and then run journalctl -fo cat /usr/bin/gnome-shell in a Terminal. After that try to tile a window again via touch. Do the location coordinates of your finger get printed? If not, did at least touch event gotten get printed?

I've just tried it on my Surface Pro 4 (first time using the touchscreen on Linux), it kind of works. But it's very broken. You can move windows horizontally, but not down, unless you maximize the window and pull it down. I'll send you a video when I have some more time.

**Comment by thelazy6** [comment]
I now have tried the `touch-grab` branch and created a screen video while reading the journal. (Many "window is moving" lines cut out).
`journalctl -fo cat /usr/bin/gnome-shell`:
```
window is moving
Error in size change accounting.
Error in size change accounting.
ATK Bridge is disabled but a11y has already been enabled.
window is moving
Using public X11 display :0, (using :1 for managed services)
Error in size change accounting.
window is moving
JS ERROR: TypeError: event is null
onWindowMoving@/home/roland/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/extension.js:499:27

window is moving
JS ERROR: TypeError: event is null
onWindowMoving@/home/roland/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/extension.js:499:27

window is moving
JS ERROR: TypeError: event is null
onWindowMoving@/home/roland/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/extension.js:499:27

window is moving

Error in size change accounting.
window is moving
Error in size change accounting.
Window manager warning: last_user_time (796567) is greater than comparison timestamp (796563).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: W24 appears to be one of the offending windows with a timestamp of 796567.  Working around...
```
Two usability issues remain:
- When trying to restore a previously maximized window by dragging the titlebar, it remains at original (maximized) size but is moved. Expected: return to size before maximizing.
- The tiling dash does not respond to touch input (btw. it is the main reason for me for using the extension).

Screen video:
https://user-images.githubusercontent.com/62787185/111902420-a2914680-8a3d-11eb-896e-099c517cbaca.mp4

**Comment by thelazy6** [comment]
I forgot to mention the most relevant part: Touch tiling now works!!!

**Comment by Leleat** [comment]
> You can move windows horizontally, but not down, unless you maximize the window and pull it down. I'll send you a video when I have some more time.

Is that what happens at the beginning of thelazy6's video?

>  When trying to restore a previously maximized window by dragging the titlebar, it remains at original (maximized) size but is moved. Expected: return to size before maximizing.

That's a separate Wayland issue. I am currently rewriting the extension and have it fixed there. I'll port it to `master` eventually. (The rewrite is probably a bit far away. For it I'll try to get a proper solution for touch events. These are just bandaid fixes and me trying to figure out how touch events work).

> The tiling dash does not respond to touch input (btw. it is the main reason for me for using the extension).

I've added a new commit to the `touch-grab` branch. Can you try it out? Can you also please try swiping on an icon and see, if the window dash opens (i. e. you get another dash with previews of the app's window(s)). Make sure the app has multiple windows open, when swiping on it.

**Comment by thelazy6** [comment]
The window dash now works fully as expected (like the Alt-Tab dash of native gnome-shell). Even with touch events. But the main tiling dash does not yet respond to touch events. Possibly the same codepiece that made the window dash work will fix the problem also for the main dash. (I cannot do much with GJS and Gnome extensions, so please review my suggestion)

**Comment by Leleat** [comment]
> (like the Alt-Tab dash of native gnome-shell)

Are you saying you can use touch with GNOME default altTab popup? On a quick glance I couldn't find code which indicates that the altTab supports touch. If you did mean that you can use touch with altTab I might need to take a closer look.

> Possibly the same codepiece that made the window dash work will fix the problem also for the main dash.

I guess you opened the window's dash with your keyboard/mouse and not with touch, right?

I've added some logs again. Can you try that and post the output of the logs again when you try to touch an app icon?

**Comment by thelazy6** [comment]
New logs: 
```
cr_declaration_parse_list_from_buf: assertion 'parser' failed
cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
cr_declaration_parse_list_from_buf: assertion 'parser' failed
cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
cr_declaration_parse_list_from_buf: assertion 'parser' failed
GNOME Shell started at Sun Mar 21 2021 15:47:24 GMT+0100 (Mitteleuropäische Normalzeit)
JS ERROR: TypeError: method Gio.File.delete_async: At least 3 arguments required, but only 2 passed
_handleLockScreenWarning@resource:///org/gnome/shell/ui/main.js:331:24
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:303:13
_startupAnimationComplete@resource:///org/gnome/shell/ui/layout.js:741:14
onComplete@resource:///org/gnome/shell/ui/layout.js:708:39
runStartupAnimation/<@resource:///org/gnome/shell/ui/overview.js:661:13
onComplete@resource:///org/gnome/shell/ui/overviewControls.js:791:31
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:85:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:168:64

Registering session with GDM
ATK Bridge is disabled but a11y has already been enabled.
Using public X11 display :0, (using :1 for managed services)
Error in size change accounting.
Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor ClutterClone is on because it needs an allocation.
Can't update stage views actor StIcon is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
_st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor ClutterClone is on because it needs an allocation.
Can't update stage views actor StIcon is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
_st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor ClutterClone is on because it needs an allocation.
Can't update stage views actor StIcon is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
_st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
```
And yes, I can use touch with GNOME default altTab popup, fully working. And the window dash I mentioned last time had nothing to do with a mouse, it was fully working touch.

This but remains:

>     * When trying to restore a previously maximized window by dragging the titlebar, it remains at original (maximized) size but is moved. Expected: return to size before maximizing.

And little other thing: The windows start tiling at ca. 1.5 cm below upper edge, this is - I think- very much. If it could be less or configurable, that would be great. Some like [this WinTile extension](https://github.com/Fmstrat/wintile).

**Comment by Leleat** [comment]
Hmm, weird. There is nothing in the logs from my extension even though I connected to the same signal as the window previews...

> I can use touch with GNOME default altTab popup, fully working

In that case maybe try the rewrite branch here https://github.com/Leleat/Tiling-Assist/tree/v2-rewrite ? In the current master I basically implemented the dash/popup myself. In the rewrite I pretty much straight up copied GNOME's altTab (rather I just call altTab's functions).

> This but remains:
>
 >  * When trying to restore a previously maximized window by dragging the titlebar, it remains at original (maximized) size but is moved. Expected: return to size before maximizing.

This is fixed in the rewrite (but not yet in master).

> The windows start tiling at ca. 1.5 cm below upper edge, this is - I think- very much. If it could be less or configurable, that would be great

I also made that configurable in the rewrite.

**Comment by thelazy6** [comment]
New logs: 
```
cr_declaration_parse_list_from_buf: assertion 'parser' failed
cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
cr_declaration_parse_list_from_buf: assertion 'parser' failed
cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
cr_declaration_parse_list_from_buf: assertion 'parser' failed
GNOME Shell started at Sun Mar 21 2021 15:47:24 GMT+0100 (Mitteleuropäische Normalzeit)
JS ERROR: TypeError: method Gio.File.delete_async: At least 3 arguments required, but only 2 passed
_handleLockScreenWarning@resource:///org/gnome/shell/ui/main.js:331:24
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:303:13
_startupAnimationComplete@resource:///org/gnome/shell/ui/layout.js:741:14
onComplete@resource:///org/gnome/shell/ui/layout.js:708:39
runStartupAnimation/<@resource:///org/gnome/shell/ui/overview.js:661:13
onComplete@resource:///org/gnome/shell/ui/overviewControls.js:791:31
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:85:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:168:64

Registering session with GDM
ATK Bridge is disabled but a11y has already been enabled.
Using public X11 display :0, (using :1 for managed services)
Error in size change accounting.
Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor ClutterClone is on because it needs an allocation.
Can't update stage views actor StIcon is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
_st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor ClutterClone is on because it needs an allocation.
Can't update stage views actor StIcon is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
_st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor ClutterClone is on because it needs an allocation.
Can't update stage views actor StIcon is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
_st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
```
And yes, I can use touch with GNOME default altTab popup, fully working. And the window dash I mentioned last time had nothing to do with a mouse, it was fully working touch.

This but remains:

>     * When trying to restore a previously maximized window by dragging the titlebar, it remains at original (maximized) size but is moved. Expected: return to size before maximizing.

And little other thing: The windows start tiling at ca. 1.5 cm below upper edge, this is - I think- very much. If it could be less or configurable, that would be great. Some like [this WinTile extension](https://github.com/Fmstrat/wintile).

**Comment by thelazy6** [comment]
Now, using the v2-rewrite branch, the dash works correctly - with touch - but the initial problem is not fixed there (as was in the last touch-grab). Again dragging a title bar with a finger to left/right edge for tiling stops working.
But I think it is only necessary to merge the two branches, we should have everything, but not in one place.

**Comment by Leleat** [comment]
>  but the initial problem is not fixed there (as was in the last touch-grab). Again dragging a title bar with a finger to left/right edge for tiling stops working.

Ops, my bad, fixed.

> But the settings dialog crashes with

Are you already on GNOME 40? 
(Note that the rewrite is a WIP and it's still misisng the layouts and the window gaps from the current master branch.)

**Comment by thelazy6** [comment]
Yes, it my machine is Fedora 34 / GNOME 40. But the settings dialog of master and touch-grab works for me.

**Comment by Leleat** [comment]
> Yes, it my machine is Fedora 34 / GNOME 40

Are you still on Wayland? 

I've added the settings now provisionally. Focus with the keyboard doesn't work properly yet though. But you should be able to access it.

**Comment by thelazy6** [comment]
Now v2-rewrite is almost perfect for tablet use. Touch input works in almost every place.
Only one (new) problem comes: When having multiple windows of one application and touch-selecting the icon in the dash (and it is not the first one in the dash), the first window of the application is tiled and the window dash does not show. With mouse it is ok. (But don't worry, this issue is also in upstream GNOME shell 40.rc, and I'll also report it there.)

**Comment by Leleat** [comment]
Nice, if gnome shell adds touch support, I'll just pull it into my extensions. No need to come up with something myself :)

One last thing: I've checked out the gnome shell's altTab code and I see nothing about touch input... So my question
Are still on Wayland on your Fedora machine?

**Comment by Leleat** [comment]
Saw your edit now, thanks.

**Comment by Turbine1991** [comment]
Here's a video of the current state of the touch branch:
https://drive.google.com/file/d/1nfDDdNFYvt7bB8QGVd5rYlrcOHpyZ6ZI/view?usp=sharing

The only tiling action I can get to work with touch, is maximize.

**Comment by thelazy6** [comment]
I can do all, but I have the (unstable) v2-rewrite branch. But the
touch changes there originated in the touch-grab branch.

Am Montag, dem 22.03.2021 um 16:13 -0700 schrieb Turbine1991:

**Comment by Leleat** [comment]
> Here's an in-person video of the current state of the touch branch:

As thelazy6 said, If you want to try touch with this extension, use the rewrite branch. The touch branch was just for testing and I've now deleted all the unused branches.

In the end I only replaced a `global.get_pointer()` call. But I still use `get_pointer()` when restoring the window's size from a tiled state... made me wonder I thelazy6 didn't mention there being something off as a bug.... ^^' So touch tiling can definetly use some rigorous testing.

**Comment by Turbine1991** [comment]
Oh cheers, I was wondering about this!

**Comment by Turbine1991** [comment]
> In the end I only replaced a global.get_pointer() call. But I still use get_pointer() when restoring the window's size from a tiled state... made me wonder I thelazy6 didn't mention there being something off as a bug.... ^^' So touch tiling can definetly use some rigorous testing.

Tiling to the left or right doesn't work via touch using the rewrite branch. It works exactly the same way. Also, if you tile to a side with the mouse, you cannot move the window vertically, only horizontally with your finger.

**Comment by Leleat** [comment]
I've pushed a new commit to adress one issue I saw in your screencap to the `rewrite` branch, please try it out @Turbine1991:
- I replaced the remaining calls of `global.get_pointer()`. This should hopefully fix the wrong position of the window when untiling it via grab. Maybe the following as well but I am just guessing here so I have no idea what could be causing it
> Also, if you tile to a side with the mouse, you cannot move the window vertically, only horizontally with your finger.

> Tiling to the left or right doesn't work via touch using the rewrite branch.
- One thing I think is weird is that you can maximize via grab but I didn't see the tile preview... I've  added some logs to the `rewrite` branch. Please post them here after trying to tile via touch. (Btw in your screencast you logged with 'journalctl -fo cat /usr/bin/**gnome-session**' Was that meant for me? I need the logs for `gnome-shell`. )

**Comment by Turbine1991** [comment]
> I replaced the remaining calls of global.get_pointer(). This should hopefully fix the wrong position of the window when untiling it via grab. Maybe the following as well but I am just guessing here so I have no idea what could be causing it.

Unfortunately this appears to still happen. I definitely used the rewrite and even restarted the machine.

> Noticed that a miminmized window in your screencast isn't shown after tiling. Fixed that in the rewrite now as well.

This fix worked.

> journalctl -fo cat /usr/bin/gnome-session' Was that meant for me?

No, it was unrelated.

Current bugs: (excluding first)
- Cannot tile to any edge, only maximize.
- After tiling to a half-edge using a mouse, it's stuck on one of the axis. So if I tile left & right, I cannot move it vertically. If I tile top and bottom, I cannot move it horizontally.

**Comment by Leleat** [comment]
> Unfortunately this appears to still happen. I definitely used the rewrite and even restarted the machine.

Sorry, which bug did you mean with that? Restoring the window at the wrong position or that if you tile to a side with the mouse, you cannot move the window vertically, only horizontally with your finger?

----

Anything in the logs?

**Comment by Turbine1991** [comment]
> Sorry, which bug did you mean with that? Restoring the window at the wrong position or that if you tile to a side with the mouse, you cannot move the window vertically, only horizontally with your finger?

It's impossible to restore the window, it just wants to stay at the tiled size and slide along the screen.

> Anything in the logs?

Uh, I'll remember to look for logs next time.

**Comment by thelazy6** [comment]
> > Sorry, which bug did you mean with that? Restoring the window at the wrong position or that if you tile to a side with the mouse, you cannot move the window vertically, only horizontally with your finger?
> 
> It's impossible to restore the window, it just wants to stay at the tiled size and slide along the screen.

For me this occurs occasionally, mostly for the first time when I tile the window. The second time it's fine. My logs:
```
Can't update stage views actor ClutterClone is on because it needs an allocation.
Can't update stage views actor StIcon is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
_st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
Can't update stage views actor ClutterClone is on because it needs an allocation.
Can't update stage views actor StIcon is on because it needs an allocation.
Can't update stage views actor ClutterActor is on because it needs an allocation.
_st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
```
An `Error in size change accounting.` line comes every time when tiling, maximizing or restoring.

**Comment by Leleat** [comment]
> An Error in size change accounting. line comes every time when tiling, maximizing or restoring.

That's related to the animation. I've 'misappropriated' one of GNOME's methods to implement the animations because it's basically just one line of code. Didn't want to come up with my own implementation. If you disable the animations, that message will disappear.

The other logs are probably not related to this extension as I don't touch the `windowPreview`.

**Comment by Turbine1991** [comment]
Is there a way we can help you sort this? Would you like access to my tablet and have me test it, I can be available for a day.

**Comment by Leleat** [comment]
> Is there a way we can help you sort this? Would you like access to my tablet and have me test it, I can be available for a day.

That would be very helpful. How do you imagine this work? Chatting over something like matrix while you 'live-test' code?

PS. I think we are from quite different timezones but I am now free for the next 2 weeks (except I won't be home around easter since I am visiting my parents) so I am fine with any time.

No big deal, if this doesn't work out. After the rewrite I was planning to ask around GNOME's help channels to see if I can find someone (who knows what they are doing and not blindly taking a stab like me ^^' ) give me some tips.

**Comment by Turbine1991** [comment]
> That would be very helpful. How do you imagine this work? Chatting over something like matrix while you 'live-test' code?

Yes, or Discord. My Discord is: nom#8164

> PS. I think we are from quite different timezones but I am now free for the next 2 weeks (except I won't be home around easter since I am visiting my parents) so I am fine with any time.

Where are you from? I live in New Zealand.

> I was planning to ask around GNOME's help channels to see if I can find someone

I do wonder how many people have experience in GTK and touch screens. 🤔

**Comment by Leleat** [comment]
> Yes, or Discord. My Discord is: nom#8164

Could't add you. Is the capitalization correct?

> Where are you from? I live in New Zealand.

GMT +1, so a 12h difference.

**Comment by Turbine1991** [comment]
> Could't add you. Is the capitalization correct?

Try NoM#8164

It must be the capitalization.

**Comment by Leleat** [comment]
> It must be the capitalization.

Yup, send you a request.

**Comment by thelazy6** [comment]
Little addition: For touchscreens, there is currently no way of exiting
the tiling dash without selecting a window. You can press Escape or
click (mouse) somewhere in the grey overlay to exit the tiling dash,
but not touching there.

Am Freitag, dem 26.03.2021 um 07:48 -0700 schrieb Leleat:

**Comment by Leleat** [comment]
> Little addition: For touchscreens, there is currently no way of exiting
the tiling dash without selecting a window. You can press Escape or
click (mouse) somewhere in the grey overlay to exit the tiling dash,
but not touching there.

Hehe, what a coincidence. Turbine and me did some testing yesterday and adressed this. Can you try the current `master` branch and see, if it's fixed for you?

**Comment by thelazy6** [comment]
Unfortunately, not fixed. Instead the restoring soes not work any more.
Logs: Many blocks like
--- window moving start ---
event.x: undefined
event.y: undefined
workArea.x: 0
workArea.y: 32
workArea.width: 1920
workArea.height: 1048
--- window moving end ---

and that's it.

Am Dienstag, dem 30.03.2021 um 04:55 -0700 schrieb Leleat:

**Comment by Leleat** [comment]
It appears you are using an outdated version. The logs were already removed. If you did update the file, I guess you didn't restart GNOME shell. On Wayland you need to log out for that.

**Comment by thelazy6** [comment]
Yes, I was still in the old 'v2-rewrite' branch, so git pull does
nothing.
Exiting the dash is now perfect, but the restore issue remains. (And
touching an application icon with multiple windows and which is not the
first in the dash).


Am Dienstag, dem 30.03.2021 um 08:13 -0700 schrieb Leleat:

**Comment by Leleat** [comment]
> but the restore issue remains. 

What is it excatly (will the window stay at the tiled size)? Did it work in the past for you (with a previours commit/branch)?

**Comment by thelazy6** [comment]
There was a commit in v2-rewrite at which it worked for the second time of 
restoring, but not for the first. And also this only sometimes.
Am Dienstag, 30. März 2021, 18:41:53 CEST schrieb Leleat:
> > but the restore issue remains.
> 
> What is it excatly (will the window stay at the tiled size)? Did it work in
> the past for you (with a previours commit/branch)?

**Comment by thelazy6** [comment]
There was a commit in v2-rewrite at which it worked for the second time of 
restoring, but not for the first. And also this only sometimes. The tiled 
window keeps its size, but moves. It can be manually resized.
Am Dienstag, 30. März 2021, 18:41:53 CEST schrieb Leleat:
> > but the restore issue remains.
> 
> What is it excatly (will the window stay at the tiled size)? Did it work in
> the past for you (with a previours commit/branch)?

**Comment by Leleat** [comment]
Don't think that is related to the `master` branch since I didn't really change anything grab related there. And around 4h ago you were still on the `v2-rewrite` branch and already had the restoring issue.

> Unfortunately, not fixed. Instead the restoring soes not work any more.
Logs: Many blocks like
--- window moving start ---
event.x: undefined
event.y: undefined
workArea.x: 0
workArea.y: 32
workArea.width: 1920
workArea.height: 1048
--- window moving end ---
>
> and that's it.

Can you test, if this is touch related and just a general Wayland issue by trying it with the mouse (Wayland in general has more issue... and in the past there was an issue related to the grab position/restoring size...)?

**Comment by thelazy6** [comment]
Mouse, touchpad and touchscreen behave the same on my wayland session.
I.E. the restoring works only the second time, and this unreliably.
Interesting that it does work sometimes... but I cannot find any
difference.

Am Dienstag, dem 30.03.2021 um 12:36 -0700 schrieb Leleat:

**Comment by Leleat** [comment]
> I.E. the restoring works only the second time, and this unreliably.

I used a timer as a workaround to restore the window size. On Wayland this caused some issues in the past but on my current machine when running Wayland it's fine. So I think it's some kinda time/race issue...

Can you still elobarte what the exact issue is, so I can be sure? Does the size only not get restored but the window still can be moved around? .... or can you not move the window at all... or only specific directions etc ?

**Comment by thelazy6** [comment]
Now I have it exactly (the apps are only for identification in the
examples, they can be substituted): 
- Tile terminal, by dash tile Nautilus, restore Terminal, restore
Nautilus: Everything correct
- Tile terminal, by dash tile Nautilus, restore Nautilus, restore
Terminal: Nautilus restores correctly, Terminal keeps its size but can
be moved (i.e. also outside the screen). Both with mouse and
touchscreen. (Yes, I just git pull'ed and reloaded the extension)



Am Mittwoch, dem 31.03.2021 um 04:32 -0700 schrieb Leleat:

**Comment by Leleat** [comment]
I've tried to reproduce it with no luck. Here is a gif:

![output](https://user-images.githubusercontent.com/53054301/113179245-f28ebb00-923e-11eb-8217-e890ca4eb775.gif)

I guess you also don't get any errors in the logs, do you?

Code-wise I am using whatever Mutter's (GNOME's window manager) API provides... In the end I don't think I can "fix it" or provide a sensible workaround. This issue is only limited to Wayland. If you are using a Xorg session, it shouldn't happen. But in that case you won't be able to use touch with this extension (looks like a Xorg limitation; related: https://gitlab.gnome.org/GNOME/mutter/-/issues/295).

-----

Any way... I am losing oversight of the remaining issues regarding touch since there are so many comments in this issue now (^^`). So if I am right, the only thing missing is a way to open the window previews via touch, right?

**Comment by Leleat** [comment]
> Wayland appears to have quite a few bugs, with a mouse. I'm not sure if it's the one he's referring to.

I am only aware of the 'restore size' issue. What are the others?

**Comment by Leleat** [comment]
@thelazy6 I've created a "workaround" branch to "fix" the restore issue here https://github.com/Leleat/Tiling-Assist/tree/restore-on-grab-end. Now the window size will restore when the **grab ends.** Can you test it?

PS. I just want to see, if the idea behind it works for now. If it does, I'll make this a setting (and need to fix old bugs which were introduced with because of this workaround).

**Comment by Leleat** [comment]
Closing this since there are too many off-topic issues in here now... As far as I can tell the only issue left for touch is opening the tiling popup's window preview. I've opened a new issue for that.

**Comment by burtvadr** [comment]
**Title**: Touch / detach not detected on secondary bottom display (Sunshine / Nintendo Switch, Wayland) — tiling options not shown

**Summary**
When using a secondary display mounted *below* my main display (two physical cables from GPU -> monitor) and Sunshine on a Nintendo Switch for touch/pen input, the extension’s detach / touch-based tiling detection fails completely. With Tiling Assistant disabled, GNOME’s native tiling behavior works normally. When TA is enabled, the default four touch/pen tiling targets (top-left, top-right, bottom-left, bottom-right) are **not detected at all** via touch/pen input. Mouse input and non-extension (GNOME default) tiling work fine. This used to happen with another extension (Alien System) so I suspect the issue is in this extension rather than Sunshine or GNOME.

I’ll attach a short video that demonstrates the issue (shows touch/pen working for GNOME default tiling, but nothing detected when Tiling Assistant enabled).

---

## Steps to reproduce

1. Boot GNOME on Wayland (Fedora 43 in my case).
2. Connect two physical display outputs from GPU to the same monitor (I have one 1920×1080 display and one 1280×720 display — the 720p is treated as a secondary bottom display).
3. Run Sunshine on Nintendo Switch to provide native pen/touch input on the secondary display.
4. Enable Tiling Assistant extension.
5. Attempt to use touch/pen to snap a window using the extension’s touch tiling targets (top-left, top-right, bottom-left, bottom-right) on either display.

## Expected behavior

When interacting with the screen with touch/pen, the Tiling Assistant should detect the touch gestures and show/accept the four tiling targets (top-left/top-right/bottom-left/bottom-right) and tile windows accordingly.

## Actual behavior

Tiling Assistant does not detect any touch/pen input for tiling targets. No tiling targets appear and no tiling action occurs when using touch/pen. Using the mouse works as expected; disabling the extension returns native GNOME tiling behavior which accepts my touch input and tiles into two large windows.

## Environment

* OS: Fedora Linux 43 (Workstation Edition) x86_64
* Kernel: 6.18.6-200.fc43.x86_64
* GNOME: 49.3
* WM: Mutter (Wayland)
* GPU: NVIDIA GeForce RTX 3060 8GB
* Displays:

  * External (secondary): 1280×720 @ 60 Hz (connected via GPU output)
  * External (main): 1920×1080 @ 180 Hz (connected via GPU output)
* Input: Sunshine (on Nintendo Switch) providing native pen/touch support on the 720p display
* Fastfetch output (paste of what I ran locally):

```
OS: Fedora Linux 43 (Workstation Edition) x86_64
Kernel: Linux 6.18.6-200.fc43.x86_64
DE: GNOME 49.3
WM: Mutter (Wayland)
Display (LG ULTRAGEAR): 1280x720 in 24", 60 Hz [External]
Display (LG ULTRAGEAR): 1920x1080 in 24", 180 Hz [External] *
GPU: NVIDIA GeForce RTX 3060 8GB [Discrete]
```

(Full fastfetch output available on request; I have a short video showing the problem.)

## Additional notes / context

* I am **not** creating a virtual display via Moonlight or similar — both displays are physically connected to the GPU via separate cables and detected by the PC.
* Secondary display is placed *below* the main display in my display layout.
* The external input source is Sunshine on a Switch (native pen/touch forwarded). I previously saw similar behavior with another extension (Alien System), which suggests the problem is likely an extension compatibility issue rather than Sunshine or GNOME.
* With Tiling Assistant **disabled**, GNOME’s default two-window tiling works and is responsive to touch/pen (so the input device and layout are usable). With Tiling Assistant enabled, the extension’s touch targets are never detected.

---

## What I can provide / attach

* Short video showing:

  * Touch/pen working with GNOME default tiling.
  * Touch/pen not detected when Tiling Assistant is enabled (no targets appear).
